### ISSUE TITLE
Compatibility with Java 11

### ISSUE THREAD

**Issue by b-fein** [ls1intum/jenkins-server-notification-plugin#14]
# Description of the Problem
Newer Jenkins versions recommend Java 11 instead of 8. The default docker image for the LTS version has recently switched to jdk11, too.
This plugin crashes when trying to parse the JUnit-XMLs in that configuration, however, and therefore fails to send anything back to Artemis. This is due to the removal of JAXB in Java 9+.

I’m not sure if the issue is caused by somehow ill-configured classloaders in my setup**s** or if it is a general problem with this plugin.

## Error Message
```
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:278)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:421)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	at de.tum.in.www1.jenkins.notifications.SendTestResultsNotificationPostBuildTask.lambda$extractTestResults$1(SendTestResultsNotificationPostBuildTask.java:116)
[…]
```

# Attempted Solutions
Jenkins provides a [JAXB-Plugin](https://plugins.jenkins.io/jaxb/#dependencies) that should provide the necessary class. This is installed. Explicitly depending on the plugin in the `pom.xml` does not solve the issue, either.

I also tried to to explicitly depend directly on the [JAXB 2.3 implementation](https://search.maven.org/artifact/com.sun.xml.bind/jaxb-impl/2.3.5/jar) in the `pom.xml`. The jar with the correct classes is placed as intended in the `hpi` plugin file. This does not resolve the error.

Using the [Jakarta XML Bindings](https://eclipse-ee4j.github.io/jaxb-ri/) did not resolve the problem, either. The error still is `java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory`. It should use ` org.glassfish.jaxb.runtime.v2.ContextFactory` that is included with the `jaxb-impl-3.0.0.jar` instead.
Explicitly changing the implementation to look for by adding
```java
class SendTestResultsNotificationPostBuildTask […] {
    // from: https://github.com/eclipse-ee4j/jaxb-api/issues/78#issuecomment-810923078
    private static final String JAXB_CONTEXT_FACTORY_IMPLEMENTATION = "org.glassfish.jaxb.runtime.v2.ContextFactory";
    static {
        System.setProperty("javax.xml.bind.JAXBContextFactory", JAXB_CONTEXT_FACTORY_IMPLEMENTATION);
        System.setProperty(JAXBContext.JAXB_CONTEXT_FACTORY, JAXB_CONTEXT_FACTORY_IMPLEMENTATION);
    }
    […]
}
```
changes the error message to `java.lang.ClassNotFoundException: org.glassfish.jaxb.runtime.v2.ContextFactory` (which is present in `WEB-INF/lib/jaxb-impl-3.0.0.jar` as part of the `hpi` file).

That is why I assume it to some kind of issue with the classloader. The [Jenkins Documentation](https://www.jenkins.io/doc/developer/plugin-development/dependencies-and-class-loading/) explains that loading a class from a jar in the WEB-INF folder should be possible.

# Replication
You can start a local Jenkins installation with `mvn hpi:run`. In http://localhost:8080/jenkins/systemInfo you can make sure that Jenkins is actually running on Java 11. If not, you can change the `JAVA_HOME` environment variable to point to the correct directory before executing the Maven command. 
This plugin is automatically installed. Additionally, install the Pipelines plugin yourself.

Alternatively, reuse an existing Jenkins installation and start it with Java 11. As long as you only change docker images from e.g. `jenkins/jenkins:lts-jdk8` to the same Jenkins version but on Java 11 `jenkins/jenkins:lts` you should be able to just switch back later on without problems.

Then you can either reuse some exercise from Artemis that uses the plugin to check if the plugin crashes in the same way as described above in the last stage or setup a minimal Pipeline-job with the following pipeline script:
```groovy
node {
    sh "mkdir -p customFeedbacks"
    sh "mkdir -p results"

    writeFile file: "customFeedbacks/test.json", text: '{ name: "sdsd2", success: true }'
    writeFile file: "results/Test.xml", text: """
    <?xml version="1.0" encoding="UTF-8"?>
    <testsuite name="de.tum.in.www1.artemis.ResultServiceIntegrationTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2021-10-18T07:34:19" hostname="omitted" time="34.754">
        <properties/>
        <testcase name="testGetResultsWithPointsForFileUploadExerciseWithGradingCriteria()" classname="de.tum.in.www1.artemis.ResultServiceIntegrationTest" time="5.263"/>
        <system-out></system-out>
        <system-err></system-err>
    </testsuite>
    """

    sendTestResults credentialsId: '300a4504-6334-4d91-a7e0-dcc5042ab831', notificationUrl: 'https://artemis.invalid.link/api/programming-exercises/new-result'
}
```
The invalid link to Artemis does not matter, as the plugin crashes even before as described above when trying to parse the JUnit-XML.

**Comment by dfuchss** [comment]
Same occurs on our production systems.

**Comment by dfuchss** [comment]
Switching from `lts` to `lts-jdk8` resolves the issue for our production system as a quick fix.

**Comment by nk-coding** [comment]
Same issue for us at University of Stuttgart
