### ISSUE TITLE
Compiling current master fails

### ISSUE THREAD

**Issue by snowball77** [ls1intum/jenkins-server-notification-plugin#4]
Result of mvn clean install using JDK 1.8:
[INFO] --- spotbugs-maven-plugin:3.1.12.2:check (spotbugs) @ test-notifications ---
[INFO] BugInstance size is 1
[INFO] Error size is 0
[INFO] Total bugs: 1
[ERROR] Possible null pointer dereference in de.tum.in.www1.jenkins.notifications.SendTestResultsNotificationPostBuildTask.perform(Run, FilePath, Launcher, TaskListener) due to return value of called method [de.tum.in.www1.jenkins.notifications.SendTestResultsNotificationPostBuildTask, de.tum.in.www1.jenkins.notifications.SendTestResultsNotificationPostBuildTask] Method invoked at SendTestResultsNotificationPostBuildTask.java:[line 78]Known null at SendTestResultsNotificationPostBuildTask.java:[line 79] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE

**Comment by kloessst** [comment]
You can use mvn clean package as a workaround. It seems like Spotbugs is bound to the install phase only.

**Comment by kloessst** [comment]
Is fixed in https://github.com/ls1intum/jenkins-server-notification-plugin/issues/4

**Comment by snowball77** [comment]
Confirmed that v1.2.1 compiles again
